services:
  - type: web
    name: samarthai-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: SUPABASE_URL
        value: https://curszxwxfujksnkihkc.supabase.co
      - key: SUPABASE_ANON_KEY
        value: sb_publishable_bQxJArHzqVUuHD-wMGkvqQ_EdPf04
      - key: SUPABASE_SERVICE_KEY
        value: sb_secret_VjrJhMAOPUiMZtot610BvW_L39FSWmI
